#!/bin/bash
#----------------------------------------"
# Contributor:  Tobias Holzmann          "
# Last Change:  November 2014            "
# Version:      3.0                      "
# Email: Tobias.Holzmann@Holzmann-cfd.de "
#----------------------------------------"


#-------------------------------------------------------------------------------

cd ${0%/*} || exit 1

echo "
\"-----------------------------------------\"
\" vim addon for highlight OpenFOAM files  \"
\" Contributor:  Tobias Holzmann           \"
\" Last Change:  November 2014             \"
\" Version:      3.0                       \"
\"-----------------------------------------\"
"


# Color definition for nice output and playing with bash
# CHANGE \033 over \e as \033 is more portable
#-------------------------------------------------------------------------------
red='\033[0;31m'
green='\033[0;32m'
nc='\033[0m'


# Checking if .vim directories are available and create if bool = false
# CHANGE Added extra folder checks
#-------------------------------------------------------------------------------

if [ ! -d $HOME/.vim ]; then
    mkdir $HOME/.vim
fi
if [ ! -d $HOME/.vim/plugin ]; then
    mkdir $HOME/.vim/plugin
fi
if [ ! -d $HOME/.vim/syntax ]; then
    mkdir $HOME/.vim/syntax
fi
if [ ! -d $HOME/.vim/colors ]; then
    mkdir $HOME/.vim/colors
fi
if [ ! -d $HOME/.vim/ftdetect ]; then
    mkdir $HOME/.vim/ftdetect
fi
if [ ! -d $HOME/.vim/syntax/foam256 ]; then
    mkdir $HOME/.vim/syntax/foam256
fi


# Copy files 
# CHANGE Removed the -u option as it causes issues on older bash shells
# -v option added for verbose output
#-------------------------------------------------------------------------------
cp -vr syntax/* $HOME/.vim/syntax/
cp -v ftdetect/* $HOME/.vim/ftdetect/
cp -v colors/* $HOME/.vim/colors/
cp -v plugin/* $HOME/.vim/plugin/


# Check if .vimrc exist, if not create one and 
# insert stuff, otherwise just add the stuff to the end of the file
# TODO - check if the input lines still available!
# CHANGE updated this section to work a little cleaner.
#-------------------------------------------------------------------------------
vimrcEdit=false

if [ ! -f "$HOME/.vimrc" ]; then
    echo -e "${red}No \$HOME/.vimrc found » created${nc}"
    touch "$HOME/.vimrc"
    vimrcEdit=true
else
    echo -e "${red}There is an existing \$HOME/.vimrc file"

    if grep -Fq "vim Extension OpenFOAM" "$HOME/.vimrc"; then
        echo "Entry of vim Extenion OpenFOAM in $HOME/.vimrc 
              found » nothing to do"
    else
        echo -e "${green}adding extension configuration to .vimrc${nc}"
        vimrcEdit=true
    fi
fi

if [ "$vimrcEdit" = true ]; then 
    {
        echo $'"------ vim Extension OpenFOAM ------'
        echo $':syntax on'
        echo $':set tabstop=4 shiftwidth=4 expandtab'
        echo $'"If you have no colorscheme set to 1'
        echo $':let g:foam_use_custom_colors=0'
        echo $'"------ vim Extension OpenFOAM ------'
    } >> "$HOME/.vimrc"
fi


# All done, say goodbye and be polite
#-------------------------------------------------------------------------------
echo -e "${nc}
vimExtensionOpenFOAM is ready to use...
Have a nice day... 
Tobias Holzmann"

#-------------------------------------------------------------------------------
